general {
    lock_cmd = lock-screen
    before_sleep_cmd = lock-screen
    after_sleep_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# listener {
#     timeout = 15
#     on-timeout = pidof hyprlock || launch-screensaver
#     # on-timeout = notify-send "Meddl Off!" "on-timeout triggered"
#     # on-resume = notify-send "Meddl On!" "on-resume triggered"
#     on-resume = pkill -f alacritty.*Screensaver
# }

listener {
    timeout = 300
    on-timeout = lock-screen
}

listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
