# rellana monitor.conf

# See https://wiki.hyprland.org/Configuring/Monitors/
monitor= eDP-1, 1920x1080@60, 0x0, 1
monitor = , preferred, 0x-1080, 1

bind = , Print, exec, hyprshot -m region --clipboard-only
bind = CTRL, Print, exec, hyprshot -m region
