# lothric monitor.conf

$MAIN_MONITOR = DP-2
$SECONDARY_MONITOR = HDMI-A-1

monitor = $MAIN_MONITOR, 3440x1440@179.99, 0x0, 1
monitor = $SECONDARY_MONITOR, 1920x1080@60, 3440x0, 1

workspace = 1, monitor:$MAIN_MONITOR
workspace = 2, monitor:$MAIN_MONITOR
workspace = 3, monitor:$MAIN_MONITOR
workspace = 4, monitor:$MAIN_MONITOR
workspace = 5, monitor:$MAIN_MONITOR
workspace = 6, monitor:$MAIN_MONITOR
workspace = 7, monitor:$MAIN_MONITOR
workspace = 8, monitor:$MAIN_MONITOR
workspace = 9, monitor:$MAIN_MONITOR
workspace = 10, monitor:$MAIN_MONITOR

bind = SUPER SHIFT CTRL, 1, movecurrentworkspacetomonitor, $MAIN_MONITOR
bind = SUPER SHIFT CTRL, 2, movecurrentworkspacetomonitor, $SECONDARY_MONITOR
