# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale


# $MAIN_MONITOR = eDP-1 # Rellana
$MAIN_MONITOR = HDMI-A-2 # Lothric
$SECONDARY_MONITOR = HDMI-A-1

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,1

monitor=$MAIN_MONITOR, 1920x1080@60, 0x0, 1
monitor=$SECONDARY_MONITOR, 1920x1080@60, 1920x0, 1
# monitor=$SECONDARY_MONITOR,1920x1080,0x0,1,mirror,$MAIN_MONITOR # mirror screens

workspace = 1, monitor:$MAIN_MONITOR
workspace = 2, monitor:$MAIN_MONITOR
workspace = 3, monitor:$MAIN_MONITOR
workspace = 4, monitor:$MAIN_MONITOR
workspace = 5, monitor:$MAIN_MONITOR
workspace = 6, monitor:$MAIN_MONITOR
workspace = 7, monitor:$MAIN_MONITOR
workspace = 8, monitor:$MAIN_MONITOR
workspace = 9, monitor:$MAIN_MONITOR
workspace = 10, monitor:$MAIN_MONITOR

bind = SUPER SHIFT CTRL, 1, movecurrentworkspacetomonitor, $MAIN_MONITOR
bind = SUPER SHIFT CTRL, 2, movecurrentworkspacetomonitor, $SECONDARY_MONITOR
