hl.config({ autogenerated = false })

terminal = "kitty"
fileManager = "nautilus"
menu = "wofi --show drun"

hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")

hl.config({
	input = {
		kb_layout = "de",
		kb_variant = "",
		kb_model = "",
		kb_options = "caps:escape",
		kb_rules = "",

		follow_mouse = 1,

		sensitivity = 0,
		touchpad = {
			natural_scroll = true,
		},
	},

	cursor = {
		hide_on_key_press = true,
	},
})

hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

-- Default Monitor
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })

require("bindings")
require("autostart")
require("looknfeel")

local handle = io.popen("hostname")
local hostname = handle:read("*a"):gsub("\n$", "")
handle:close()

if hostname == "lothric" then
	require("override_lothric")
elseif hostname == "thiollier" then
	require("override_thiollier")
end
